### ISSUE TITLE
'System.Net.Http.HttpRequestException' when attempting to login to Last.fm

### ISSUE THREAD

**Issue by w41g87** [RegorForgot/LastfmDiscordRPC#6] opened 2024-05-11 18:32 UTC
After clicking on `log into` button and the browser popped up, I clicked on `grant access`.

After which the app still shows "not logged in" and the log says:
`ERR : Exception of type 'System.Net.Http.HttpRequestException' was thrown.
`

**Comment by RegorForgot** [comment] 2024-05-11 18:35
Hi, can you please send the log file found through in About section? That contains some additional information. I'll take a look and get back to you tomorrow to see what's wrong.

**Comment by w41g87** [comment] 2024-05-11 18:42
Of course. It is attached here.
[log.log](https://github.com/RegorForgot/LastfmDiscordRPC/files/15283996/log.log)

**Comment by RegorForgot** [comment] 2024-05-11 18:43
Very strange, it doesn't report what the issue is... I'll investigate the issue tomorrow, thanks for letting me know

**Comment by w41g87** [comment] 2024-05-11 18:45
If you need more information, I am using Edge on Windows 11, and is using Mullvad VPN. I have fast.fm's local scrobbler installed and running in the background.

**Comment by RegorForgot** [comment] 2024-05-12 04:49
I see what the issue is now. The free web host I'm using for creating the MD5 hash is just... dead. It's not working, even though it's supposed to. I kind of have to buy a domain/host now (which I had been planning to do), but I can't yet do that. In the meantime, I might make a new application and have it authenticate through that instead? Or I might just buy the host and get it over and done with. Apologies for the inconvenience

**Comment by RegorForgot** [comment] 2024-05-12 06:00
Hi, please check if the following build works for you, I got it working on my side:

[win8-x64.zip](https://github.com/RegorForgot/LastfmDiscordRPC/files/15285210/win8-x64.zip)

**Comment by RegorForgot** [comment] 2024-05-12 13:27
Should be fixed in [v2.1.0](https://github.com/RegorForgot/LastfmDiscordRPC/releases/2.1.0)

**Closed** 2024-05-12 15:37 UTC
